### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by bartos100** [screeps/ide#1]
[Enter steps to reproduce:]

1. created a new branch thru the web client while atom was open
2. restarting atom seems to work and shows the new branch

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: [screeps-ide](https://github.com/screeps/ide) package 0.1.2

### Stack Trace

Uncaught TypeError: Cannot convert undefined or null to object

```
At C:\Users\Bartos\.atom\packages\screeps-ide\node_modules\rxjs\internal\util\hostReportError.js:4

TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at store_1.default.reducer (/packages/screeps-ide/dist/src/components/screeps-panel/reducers/update.js:9:29)
    at /packages/screeps-ide/dist/src/store/index.js:15:17)
    at MapSubscriber._next (/packages/screeps-ide/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/packages/screeps-ide/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Subject.next (/packages/screeps-ide/node_modules/rxjs/internal/Subject.js:60:25)
    at Object.dispatch (/packages/screeps-ide/dist/src/store/index.js:9:11)
    at /packages/screeps-ide/dist/src/components/screeps-panel/index.js:58:37)
    at TapSubscriber._next (/packages/screeps-ide/node_modules/rxjs/internal/operators/tap.js:59:27)
    at TapSubscriber.Subscriber.next (/packages/screeps-ide/node_modules/rxjs/internal/Subscriber.js:66:18)
    at /packages/screeps-ide/dist/src/socket/index.js:67:26)
    at SafeSubscriber.__tryOrUnsub (/packages/screeps-ide/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/packages/screeps-ide/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/packages/screeps-ide/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/packages/screeps-ide/node_modules/rxjs/internal/Subscriber.js:66:18)
    at FilterSubscriber._next (/packages/screeps-ide/node_modules/rxjs/internal/operators/filter.js:52:30)
    at FilterSubscriber.Subscriber.next (/packages/screeps-ide/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeUntilSubscriber.Subscriber._next (/packages/screeps-ide/node_modules/rxjs/internal/Subscriber.js:89:26)
    at TakeUntilSubscriber.Subscriber.next (/packages/screeps-ide/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Subject.next (/packages/screeps-ide/node_modules/rxjs/internal/Subject.js:60:25)
    at SockJS.Socket._socket.onmessage (/packages/screeps-ide/dist/src/socket/index.js:41:31)
    at SockJS.EventTarget.dispatchEvent (/packages/screeps-ide/node_modules/sockjs-client/lib/event/eventtarget.js:51:20)
    at /packages/screeps-ide/node_modules/sockjs-client/lib/main.js:279:16
    at Array.forEach (<anonymous>)
    at SockJS._transportMessage (/packages/screeps-ide/node_modules/sockjs-client/lib/main.js:277:17)
    at WebSocketTransport.emit (events.js:182:13)
    at Client.WebSocketTransport.ws.onmessage (/packages/screeps-ide/node_modules/sockjs-client/lib/transport/websocket.js:35:10)
    at Client.dispatchEvent (/packages/screeps-ide/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:24:30)
    at Client._receiveMessage (/packages/screeps-ide/node_modules/faye-websocket/lib/faye/websocket/api.js:152:10)
    at /packages/screeps-ide/node_modules/faye-websocket/lib/faye/websocket/api.js:36:49)
```

### Commands

```
```

### Non-Core Packages

```
atom-ternjs-screeps 1.21.0 
screeps-ide 0.1.2 
```

**Comment by tehfiend** [comment]
I was able to duplicate this error.

**Comment by Sobes76rus** [comment]
Hello! Is there are a way to solve this issue?
